### ISSUE TITLE
GeoPoint type not working

### ISSUE THREAD

**Issue by muneebs** [BlueEastCode/loopback-graphql-relay#1]
Hi I'm getting this error on the GeoPoint type.

Error: user.lastLocation field type must be Output Type but got: null.

**Comment by artalat** [comment]
This is a known issue, but definitely something we want to implement. I'll try to push a fix over the weekend.

**Comment by muneebs** [comment]
Thanks @artalat, much appreciated.

**Comment by artalat** [comment]
Latest release resolves this issue.
