### ISSUE TITLE
Error: Callback is not a function

### ISSUE THREAD

**Issue by prateekrastogi** [BlueEastCode/loopback-graphql-relay#21]
Hi,
I am trying to run graphql queries for a simple remote method of http verb get. And, I kept getting the error that callback is not a function . What's the workaround for it as by default in loopback we pass the return value to callback function for returning values from our rest api. Also, the default model methods are working properly while querying. Am i missing something?

**Comment by prateekrastogi** [comment]
Hi, 
As i was seeing the code i saw a commit that disable queries and mutations for remote static methods. Would like to know the reasoning behind it so may be i can try adding that support

**Comment by aatifhussain** [comment]
@prateekrastogi Issue is solved. @bjavaid Issue should be closed.
