### ISSUE TITLE
How to use subscription ? 

### ISSUE THREAD

**Issue by adamsaparudin** [BlueEastCode/loopback-graphql-relay#3]
Hello, 

I was try create mutation on localhost:3000/graphiql like this
`
mutation {
  Notification {
    notificationCreate(input:{data:{
      verb:"test"
    }}) {
      obj {
        verb
        userId
      }
    }
  }
}`

and subscription on localhost:3000/graphiql like this 
`subscription {
  notification(input: {create:true, update:true, remove:true}) {
    notification {
      id
      verb
    }
  }
}`

but it won't show anything on subscription page. data is success and already created.

**Comment by saadbinsaeed** [comment]
Hi @adamsaparudin, 

Sorry for the late response. You need to install the latest release (0.9.0)  of the [package](https://www.npmjs.com/package/loopback-graphql-relay). Recently we have fixed some issues with subscriptions, hope it will work.

Support of the subscriptions on graphiql is on the road map (currently not available).

First execute the query then use the **subscribeToMore** function of [apollo-client](http://dev.apollodata.com/react/subscriptions.html).

In case of any issue or you need further support, please, let us know.

**Comment by aatifhussain** [comment]
@adamsaparudin We have implemented Subscription, your mutation and subscription should work now with the latest version.
